/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HelloCheckerboardSolution {
    'size': number;
  }
  interface HelloCheckerboardSolutionAttributes extends StencilHTMLAttributes {
    'size'?: number;
  }

  interface HelloCheckerboard {}
  interface HelloCheckerboardAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'HelloCheckerboardSolution': Components.HelloCheckerboardSolution;
    'HelloCheckerboard': Components.HelloCheckerboard;
  }

  interface StencilIntrinsicElements {
    'hello-checkerboard-solution': Components.HelloCheckerboardSolutionAttributes;
    'hello-checkerboard': Components.HelloCheckerboardAttributes;
  }


  interface HTMLHelloCheckerboardSolutionElement extends Components.HelloCheckerboardSolution, HTMLStencilElement {}
  var HTMLHelloCheckerboardSolutionElement: {
    prototype: HTMLHelloCheckerboardSolutionElement;
    new (): HTMLHelloCheckerboardSolutionElement;
  };

  interface HTMLHelloCheckerboardElement extends Components.HelloCheckerboard, HTMLStencilElement {}
  var HTMLHelloCheckerboardElement: {
    prototype: HTMLHelloCheckerboardElement;
    new (): HTMLHelloCheckerboardElement;
  };

  interface HTMLElementTagNameMap {
    'hello-checkerboard-solution': HTMLHelloCheckerboardSolutionElement
    'hello-checkerboard': HTMLHelloCheckerboardElement
  }

  interface ElementTagNameMap {
    'hello-checkerboard-solution': HTMLHelloCheckerboardSolutionElement;
    'hello-checkerboard': HTMLHelloCheckerboardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
