/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilHelloSolution {}
  interface StencilHelloSolutionAttributes extends StencilHTMLAttributes {}

  interface StencilHelloSolution {}
  interface StencilHelloSolutionAttributes extends StencilHTMLAttributes {}

  interface StencilHello {}
  interface StencilHelloAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'StencilHelloSolution': Components.StencilHelloSolution;
    'StencilHelloSolution': Components.StencilHelloSolution;
    'StencilHello': Components.StencilHello;
  }

  interface StencilIntrinsicElements {
    'stencil-hello-solution': Components.StencilHelloSolutionAttributes;
    'stencil-hello-solution': Components.StencilHelloSolutionAttributes;
    'stencil-hello': Components.StencilHelloAttributes;
  }


  interface HTMLStencilHelloSolutionElement extends Components.StencilHelloSolution, HTMLStencilElement {}
  var HTMLStencilHelloSolutionElement: {
    prototype: HTMLStencilHelloSolutionElement;
    new (): HTMLStencilHelloSolutionElement;
  };

  interface HTMLStencilHelloSolutionElement extends Components.StencilHelloSolution, HTMLStencilElement {}
  var HTMLStencilHelloSolutionElement: {
    prototype: HTMLStencilHelloSolutionElement;
    new (): HTMLStencilHelloSolutionElement;
  };

  interface HTMLStencilHelloElement extends Components.StencilHello, HTMLStencilElement {}
  var HTMLStencilHelloElement: {
    prototype: HTMLStencilHelloElement;
    new (): HTMLStencilHelloElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-hello-solution': HTMLStencilHelloSolutionElement
    'stencil-hello-solution': HTMLStencilHelloSolutionElement
    'stencil-hello': HTMLStencilHelloElement
  }

  interface ElementTagNameMap {
    'stencil-hello-solution': HTMLStencilHelloSolutionElement;
    'stencil-hello-solution': HTMLStencilHelloSolutionElement;
    'stencil-hello': HTMLStencilHelloElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
