/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilTodoitemSolution {
    'completed': boolean;
    'text': string;
    'uid': number;
  }
  interface StencilTodoitemSolutionAttributes extends StencilHTMLAttributes {
    'completed'?: boolean;
    'onTodoCompleted'?: (event: CustomEvent) => void;
    'text'?: string;
    'uid'?: number;
  }

  interface StencilTodoitem {
    'completed': boolean;
    'text': string;
    'uid': number;
  }
  interface StencilTodoitemAttributes extends StencilHTMLAttributes {
    'completed'?: boolean;
    'text'?: string;
    'uid'?: number;
  }

  interface StencilTodolistSolution {}
  interface StencilTodolistSolutionAttributes extends StencilHTMLAttributes {}

  interface StencilTodolist {}
  interface StencilTodolistAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'StencilTodoitemSolution': Components.StencilTodoitemSolution;
    'StencilTodoitem': Components.StencilTodoitem;
    'StencilTodolistSolution': Components.StencilTodolistSolution;
    'StencilTodolist': Components.StencilTodolist;
  }

  interface StencilIntrinsicElements {
    'stencil-todoitem-solution': Components.StencilTodoitemSolutionAttributes;
    'stencil-todoitem': Components.StencilTodoitemAttributes;
    'stencil-todolist-solution': Components.StencilTodolistSolutionAttributes;
    'stencil-todolist': Components.StencilTodolistAttributes;
  }


  interface HTMLStencilTodoitemSolutionElement extends Components.StencilTodoitemSolution, HTMLStencilElement {}
  var HTMLStencilTodoitemSolutionElement: {
    prototype: HTMLStencilTodoitemSolutionElement;
    new (): HTMLStencilTodoitemSolutionElement;
  };

  interface HTMLStencilTodoitemElement extends Components.StencilTodoitem, HTMLStencilElement {}
  var HTMLStencilTodoitemElement: {
    prototype: HTMLStencilTodoitemElement;
    new (): HTMLStencilTodoitemElement;
  };

  interface HTMLStencilTodolistSolutionElement extends Components.StencilTodolistSolution, HTMLStencilElement {}
  var HTMLStencilTodolistSolutionElement: {
    prototype: HTMLStencilTodolistSolutionElement;
    new (): HTMLStencilTodolistSolutionElement;
  };

  interface HTMLStencilTodolistElement extends Components.StencilTodolist, HTMLStencilElement {}
  var HTMLStencilTodolistElement: {
    prototype: HTMLStencilTodolistElement;
    new (): HTMLStencilTodolistElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-todoitem-solution': HTMLStencilTodoitemSolutionElement
    'stencil-todoitem': HTMLStencilTodoitemElement
    'stencil-todolist-solution': HTMLStencilTodolistSolutionElement
    'stencil-todolist': HTMLStencilTodolistElement
  }

  interface ElementTagNameMap {
    'stencil-todoitem-solution': HTMLStencilTodoitemSolutionElement;
    'stencil-todoitem': HTMLStencilTodoitemElement;
    'stencil-todolist-solution': HTMLStencilTodolistSolutionElement;
    'stencil-todolist': HTMLStencilTodolistElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
