/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilCardSolution {}
  interface StencilCardSolutionAttributes extends StencilHTMLAttributes {}

  interface StencilCard {}
  interface StencilCardAttributes extends StencilHTMLAttributes {}

  interface StencilUsersSolution {}
  interface StencilUsersSolutionAttributes extends StencilHTMLAttributes {}

  interface StencilUsers {}
  interface StencilUsersAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'StencilCardSolution': Components.StencilCardSolution;
    'StencilCard': Components.StencilCard;
    'StencilUsersSolution': Components.StencilUsersSolution;
    'StencilUsers': Components.StencilUsers;
  }

  interface StencilIntrinsicElements {
    'stencil-card-solution': Components.StencilCardSolutionAttributes;
    'stencil-card': Components.StencilCardAttributes;
    'stencil-users-solution': Components.StencilUsersSolutionAttributes;
    'stencil-users': Components.StencilUsersAttributes;
  }


  interface HTMLStencilCardSolutionElement extends Components.StencilCardSolution, HTMLStencilElement {}
  var HTMLStencilCardSolutionElement: {
    prototype: HTMLStencilCardSolutionElement;
    new (): HTMLStencilCardSolutionElement;
  };

  interface HTMLStencilCardElement extends Components.StencilCard, HTMLStencilElement {}
  var HTMLStencilCardElement: {
    prototype: HTMLStencilCardElement;
    new (): HTMLStencilCardElement;
  };

  interface HTMLStencilUsersSolutionElement extends Components.StencilUsersSolution, HTMLStencilElement {}
  var HTMLStencilUsersSolutionElement: {
    prototype: HTMLStencilUsersSolutionElement;
    new (): HTMLStencilUsersSolutionElement;
  };

  interface HTMLStencilUsersElement extends Components.StencilUsers, HTMLStencilElement {}
  var HTMLStencilUsersElement: {
    prototype: HTMLStencilUsersElement;
    new (): HTMLStencilUsersElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-card-solution': HTMLStencilCardSolutionElement
    'stencil-card': HTMLStencilCardElement
    'stencil-users-solution': HTMLStencilUsersSolutionElement
    'stencil-users': HTMLStencilUsersElement
  }

  interface ElementTagNameMap {
    'stencil-card-solution': HTMLStencilCardSolutionElement;
    'stencil-card': HTMLStencilCardElement;
    'stencil-users-solution': HTMLStencilUsersSolutionElement;
    'stencil-users': HTMLStencilUsersElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
